### ISSUE TITLE
Replace badges with new ones for 2017

### ISSUE THREAD

**Issue by m1ghtym0** [ctfs/write-ups-2017#31]
Please create new badges for this repo

**Comment by tjgerot** [comment]
Will do.

**Comment by tjgerot** [comment]
@m1ghtym0 Let me know what you think! Commit: https://github.com/ctfs/write-ups-2017/commit/e65dee944dbaecfd750ec164a352fcfdc45b11d3

**Comment by m1ghtym0** [comment]
thanks:-)
