### ISSUE TITLE
CTF spanning over different years?

### ISSUE THREAD

**Issue by ZetaTwo** [ctfs/write-ups-2017#525]
Should a CTF that starts in 2016 and ends in 2017 be added to the 2016 or 2017 repo? In this particular case the RHME2 hardware CTF.

**Comment by m1ghtym0** [comment]
I would add it to 2016 if there's no particular reason why it would fit better in 2017.

**Comment by ZetaTwo** [comment]
Agree, will do a PR on that repo later then.
